const state={setups:[],mode:'SCALP',filter:'ALL',config:null,market:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));
const n=v=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString('de-DE',{maximumFractionDigits:8});
const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`;
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function base64ToBytes(base64){const pad='='.repeat((4-base64.length%4)%4);const raw=atob((base64+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function enableNotifications(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){toast('Push wird von diesem Browser nicht unterstützt');return false}const permission=await Notification.requestPermission();if(permission!=='granted'){toast('Benachrichtigungen wurden nicht erlaubt');return false}const registration=await navigator.serviceWorker.register('/sw.js');const config=await(await fetch('/notifications/config')).json();if(!config.public_key){toast('OS-Push ist noch nicht auf dem Server konfiguriert');return true}let subscription=await registration.pushManager.getSubscription();if(!subscription){subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(config.public_key)})}await fetch('/notifications/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(subscription.toJSON())});toast('🔔 Benachrichtigungen aktiviert');if($('#notifyBtn'))$('#notifyBtn').textContent='🔔✓';if($('#notifySettingsBtn'))$('#notifySettingsBtn').textContent='Aktiv';return true}
async function testNotification(){if(Notification.permission==='granted'){new Notification('TradeBot AI',{body:'Benachrichtigungen funktionieren lokal.',icon:'/icon-192.svg'});toast('Test-Benachrichtigung gesendet')}else await enableNotifications()}

function setupCard(s){const l=s.side==='LONG';const readiness=s.model_ready?'AI MODEL':'RULE';return `<article class="glass setup-card"><div class="setup-top"><div><span class="symbol">${escapeHtml(s.symbol)}</span> <span class="badge ${l?'side-long':'side-short'}">${s.side}</span> <span class="badge">${s.mode}</span> <span class="badge">${readiness}</span></div><div class="score">${s.confidence}<span>/100</span></div></div><div class="setup-price">${n(s.entry)}</div><div class="setup-meta"><div><small>PROBABILITY</small><b>${pct(s.probability)}</b></div><div><small>EV</small><b>${Number(s.expected_value_r)>=0?'+':''}${Number(s.expected_value_r||0).toFixed(2)}R</b></div><div><small>R:R</small><b>1:${s.risk_reward}</b></div></div><div class="setup-meta"><div><small>STOP</small><b>${n(s.stop_loss)}</b></div><div><small>TP1</small><b>${n(s.take_profit_1)}</b></div><div><small>TP2</small><b>${n(s.take_profit_2)}</b></div></div><div class="setup-meta"><div><small>SWING LOW</small><b>${n(s.swing_low)}</b></div><div><small>SWING HIGH</small><b>${n(s.swing_high)}</b></div><div><small>TRAIL</small><b>${n(s.trailing_stop)}</b></div></div><div class="setup-meta"><div><small>FIB 38.2</small><b>${n(s.fib_382)}</b></div><div><small>FIB 61.8</small><b>${n(s.fib_618)}</b></div><div><small>TF</small><b>${(s.analysis_timeframes||[]).join(' · ')}</b></div></div><div class="setup-reason">${(s.reasons||[]).slice(0,4).map(escapeHtml).join(' · ')}</div><div class="trade-actions"><button class="${l?'buy':'sell'}" data-side="${s.side}" data-symbol="${s.symbol}" data-mode="${s.mode}">${l?'LONG eröffnen':'SHORT eröffnen'}</button></div></article>`}
function renderSetups(){let list=state.setups.filter(s=>state.filter==='ALL'||state.filter===s.side||state.filter===s.mode);$('#setupGrid').innerHTML=list.length?list.slice(0,12).map(setupCard).join(''):`<div class="empty-state"><strong>Keine qualifizierten ${state.mode}-Setups.</strong><br><small style="display:block;margin-top:8px">Der Scanner hat Live-Daten analysiert. Es wird nur angezeigt, wenn die aktuellen Bedingungen den eingestellten Filter erfüllen.</small></div>`;$('#setupCount').textContent=state.setups.length;bindTrades();renderScanner()}
function renderScanner(){let list=state.setups.filter(s=>state.filter==='ALL'||state.filter===s.side||state.filter===s.mode);$('#scannerTable').innerHTML=list.length?'<div class="scanner-row header"><span>SYMBOL</span><span>SEITE</span><span>MODE</span><span>P</span><span>EV</span><span>ENTRY</span><span></span></div>'+list.map(s=>`<div class="scanner-row"><strong>${escapeHtml(s.symbol)}</strong><span class="${s.side==='LONG'?'side-long':'side-short'}">${s.side}</span><span>${s.mode}</span><strong>${pct(s.probability)}</strong><span>${Number(s.expected_value_r)>=0?'+':''}${Number(s.expected_value_r||0).toFixed(2)}R</span><span>${n(s.entry)}</span><button class="ghost-btn" data-side="${s.side}" data-symbol="${s.symbol}" data-mode="${s.mode}">Paper Trade</button></div>`).join(''):'<div class="empty-state">Keine qualifizierten Setups im aktuellen Filter.</div>';bindTrades()}
function bindTrades(){$$('[data-side]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await fetch(`/trade/${b.dataset.mode}/${b.dataset.side}/${b.dataset.symbol}`,{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.detail||'Trade abgelehnt');toast(`${b.dataset.mode} ${b.dataset.side} ${b.dataset.symbol} eröffnet`);await loadPositions()}catch(e){toast(e.message)}finally{b.disabled=false}})}
function renderMarket(){const items=state.market||[];$('#marketGrid').innerHTML=items.length?items.map(m=>`<article class="glass market-card"><div><strong>${escapeHtml(m.symbol)}</strong><span class="market-price">${n(m.price)}</span></div><b class="${Number(m.change_30m_pct)>=0?'side-long':'side-short'}">${Number(m.change_30m_pct)>=0?'+':''}${Number(m.change_30m_pct||0).toFixed(2)}%</b></article>`).join(''):'<div class="empty-state">Keine Live-Marktdaten verfügbar.</div>';const now=new Date();$('#marketUpdated').textContent=`Update ${now.toLocaleTimeString('de-DE')}`}
async function loadMarket(){try{const r=await fetch('/market/overview',{cache:'no-store'});const d=await r.json();state.market=d.items||[];renderMarket();if(state.market.length)$('#settingsLiveData').textContent='ONLINE'}catch{$('#settingsLiveData').textContent='OFFLINE'}}
async function loadConfig(){try{const d=await(await fetch('/',{cache:'no-store'})).json();state.config=d;const scalp=d.modes.SCALP,swing=d.modes.SWING;$('#scalpThreshold').textContent=`${scalp.min_confidence}+`;$('#swingThreshold').textContent=`${swing.min_confidence}+`;$('#scalpMax').textContent=scalp.max_positions;$('#swingMax').textContent=swing.max_positions;$('#maxTrades').textContent=`Max. ${state.mode==='SCALP'?scalp.max_positions:swing.max_positions}`;$('#scalpModel').textContent=scalp.model_ready?'AI MODEL READY':'RULE FALLBACK';$('#swingModel').textContent=swing.model_ready?'AI MODEL READY':'RULE FALLBACK';$('#settingsScalpModel').textContent=scalp.model_ready?'READY':'FALLBACK';$('#settingsSwingModel').textContent=swing.model_ready?'READY':'FALLBACK';$('#settingsScalpConfidence').value=scalp.min_confidence;$('#settingsSwingConfidence').value=swing.min_confidence;$('#paperLabel').textContent=d.paper_trading?'PAPER TRADING':'LIVE EXECUTION'}catch{}}

async function scanAll(){const b=$('#scanBtn');b.disabled=true;b.textContent='⟳ Live Multi-TF Scan…';const secondary=$('#scanSecondary');if(secondary)secondary.disabled=true;try{const r=await fetch('/scan/all',{cache:'no-store'});const d=await r.json();const scalp=d.SCALP||{},swing=d.SWING||{};state.setups=(d.setups||[]).sort((a,b)=>(b.probability??0)-(a.probability??0));$('#scalpSignals').textContent=scalp.qualified??0;$('#swingSignals').textContent=swing.qualified??0;$('#scanSummary').textContent=`${scalp.scanned||0}+${swing.scanned||0} Märkte · ${d.qualified_total||0} qualifiziert`;$('#scannerSummary').textContent=`SCALP: ${scalp.qualified||0} · SWING: ${swing.qualified||0} · ${scalp.rejected+swing.rejected||0} verworfen · ${scalp.errors+swing.errors||0} Fehler`;$('#scalpModel').textContent=scalp.model_ready?'AI MODEL READY':'RULE FALLBACK';$('#swingModel').textContent=swing.model_ready?'AI MODEL READY':'RULE FALLBACK';renderSetups();const best=state.setups[0];$('#confidence').textContent=best?Math.round((best.probability||0)*100):'—';if(best)toast(`${d.qualified_total||0} qualifizierte Setups · bester Score ${pct(best.probability)}`);else toast('Live-Scan abgeschlossen · keine qualifizierten Setups')}catch(e){toast('Live-Scanner nicht erreichbar');$('#engineLabel').textContent='Scanner offline'}finally{b.disabled=false;b.textContent='⚡ Live Scan';if(secondary)secondary.disabled=false}}
async function loadPositions(){try{const r=await fetch('/positions',{cache:'no-store'}),d=await r.json();$('#equity').textContent=money(d.equity);$('#pnl').innerHTML=`${money(d.realized_pnl)} <span>${d.equity?((d.realized_pnl/d.equity)*100).toFixed(2):'0.00'}%</span>`;$('#openTrades').textContent=(d.positions||[]).length;$('#maxTrades').textContent=`Max. ${state.mode==='SCALP'?(state.config?.modes?.SCALP?.max_positions??'—'):(state.config?.modes?.SWING?.max_positions??'—')}`;$('#dailyPnl').textContent=money(d.realized_pnl);$('#positionsGrid').innerHTML=d.positions?.length?d.positions.map(p=>`<article class="glass position-card"><div class="position-top"><strong>${escapeHtml(p.symbol)}</strong><span class="${p.side==='LONG'?'side-long':'side-short'}">${p.side} · ${p.mode}</span></div><div class="position-pnl">${n(p.entry)} → ${n(p.take_profit)}</div><div class="position-bar"><i></i></div><p style="color:var(--muted);font-size:11px">SL ${n(p.stop_loss)} · TP1/TP2 ${n(p.take_profit)} · Trail ${n(p.trailing_stop)} · ${p.timeframe}</p></article>`).join(''):'<div class="empty-state">Keine offenen Paper-Trades.</div>'}catch{}}
async function loadHealth(){try{const h=await(await fetch('/health',{cache:'no-store'})).json();$('#engineLabel').textContent=h.status==='ok'&&h.collector_running?'Engine online · Live Collector':'Engine online';$('#engineLabel').style.color=h.collector_running?'':'var(--red)'}catch{$('#engineLabel').textContent='Engine offline';$('#engineLabel').style.color='var(--red)'}}
async function loadHistory(){try{const d=await(await fetch('/data/analyses?limit=30',{cache:'no-store'})).json();const items=d.items||[];$('#historyGrid').innerHTML=items.length?`<div class="scanner-list">${items.map(x=>`<div class="scanner-row"><strong>${escapeHtml(x.symbol)}</strong><span class="${x.side==='LONG'?'side-long':'side-short'}">${x.side}</span><span>${x.mode}</span><span>${(Number(x.probability||0)*100).toFixed(1)}%</span><span>${Number(x.expected_value_r||0)>=0?'+':''}${Number(x.expected_value_r||0).toFixed(2)}R</span><span>${escapeHtml(x.model_version)}</span></div>`).join('')}</div>`:'<div class="empty-state">Noch keine gespeicherten Analysen.</div>'}catch{}}

async function mountStrategyProfiles(){const root=$('#settings');if(!root||$('#strategyProfiles'))return;const wrap=document.createElement('div');wrap.id='strategyProfiles';wrap.className='settings-grid';wrap.style.marginTop='14px';wrap.innerHTML=`<section class="glass setting-card"><span class="eyebrow">SCALP PROFILE</span><h3>SCALP · 5m</h3><label>Stop Loss <input id="scalpSlAtr" type="number" min="0.1" max="10" step="0.05"></label><small style="color:var(--muted)">ATR-Multiplikator</small><label>TP1 <input id="scalpTp1" type="number" min="0.2" max="20" step="0.1"></label><small style="color:var(--muted)">Risk/Reward in R</small><label>TP2 <input id="scalpTp2" type="number" min="0.5" max="50" step="0.1"></label><small style="color:var(--muted)">Risk/Reward in R</small></section><section class="glass setting-card"><span class="eyebrow">SWING PROFILE</span><h3>SWING · 1h</h3><label>Stop Loss <input id="swingSlAtr" type="number" min="0.1" max="10" step="0.05"></label><small style="color:var(--muted)">ATR-Multiplikator</small><label>TP1 <input id="swingTp1" type="number" min="0.2" max="20" step="0.1"></label><small style="color:var(--muted)">Risk/Reward in R</small><label>TP2 <input id="swingTp2" type="number" min="0.5" max="50" step="0.1"></label><small style="color:var(--muted)">Risk/Reward in R</small></section>`;root.appendChild(wrap);const load=async()=>{try{const s=await(await fetch('/notifications/settings',{cache:'no-store'})).json();$('#scalpSlAtr').value=s.scalp_sl_atr;$('#scalpTp1').value=s.scalp_tp1_rr;$('#scalpTp2').value=s.scalp_tp2_rr;$('#swingSlAtr').value=s.swing_sl_atr;$('#swingTp1').value=s.swing_tp1_rr;$('#swingTp2').value=s.swing_tp2_rr}catch{}};const save=async()=>{try{const base=await(await fetch('/notifications/settings',{cache:'no-store'})).json();const body={...base,scalp_sl_atr:Number($('#scalpSlAtr').value),scalp_tp1_rr:Number($('#scalpTp1').value),scalp_tp2_rr:Number($('#scalpTp2').value),swing_sl_atr:Number($('#swingSlAtr').value),swing_tp1_rr:Number($('#swingTp1').value),swing_tp2_rr:Number($('#swingTp2').value)};const r=await fetch('/notifications/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Profile konnte nicht gespeichert werden');toast('SCALP/SWING TP/SL gespeichert');await loadConfig()}catch(e){toast(e.message)}};['scalpSlAtr','scalpTp1','scalpTp2','swingSlAtr','swingTp1','swingTp2'].forEach(id=>$(('#'+id))?.addEventListener('change',save));await load()}

$$('.nav-item').forEach(b=>b.onclick=async()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));$('#pageTitle').textContent=b.querySelector('span').textContent;if(b.dataset.view==='settings'){await mountStrategyProfiles()}if(b.dataset.view==='history')await loadHistory()});
$$('.mode').forEach(b=>b.onclick=async()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;$('#maxTrades').textContent=`Max. ${state.config?.modes?.[state.mode]?.max_positions??'—'}`;await scanAll()});
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderSetups()});
$('#scanBtn').onclick=scanAll;$('#scanSecondary').onclick=scanAll;$('#refreshBtn').onclick=async()=>{await Promise.all([loadConfig(),loadMarket(),loadPositions(),loadHealth()]);await scanAll()};$('#notifyBtn').onclick=enableNotifications;$('#notifySettingsBtn').onclick=testNotification;$('#killSwitch').onclick=()=>{toast('Emergency Stop aktiviert — neue Trades blockieren');$('#engineLabel').textContent='Emergency stop aktiv';$('#engineLabel').style.color='var(--red)'};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});

(async function init(){await loadConfig();await Promise.all([loadMarket(),loadPositions(),loadHealth()]);await mountStrategyProfiles();await scanAll();setInterval(loadMarket,15000);setInterval(loadPositions,5000);setInterval(loadHealth,10000);setInterval(scanAll,30000)})();