const state={setups:[],mode:'SCALP',filter:'ALL'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(v||0);
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function base64ToBytes(base64){const pad='='.repeat((4-base64.length%4)%4);const raw=atob((base64+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
async function enableNotifications(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){toast('Push wird von diesem Browser nicht unterstützt');return false}const permission=await Notification.requestPermission();if(permission!=='granted'){toast('Benachrichtigungen wurden nicht erlaubt');return false}const registration=await navigator.serviceWorker.register('/sw.js');const config=await(await fetch('/notifications/config')).json();if(!config.public_key){toast('OS-Push ist noch nicht auf dem Server konfiguriert');return true}let subscription=await registration.pushManager.getSubscription();if(!subscription){subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(config.public_key)})}await fetch('/notifications/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(subscription.toJSON())});toast('🔔 Benachrichtigungen aktiviert');if($('#notifyBtn'))$('#notifyBtn').textContent='🔔';if($('#notifySettingsBtn'))$('#notifySettingsBtn').textContent='Aktiv';return true}
async function testNotification(){if(Notification.permission==='granted'){new Notification('TradeBot AI',{body:'Benachrichtigungen funktionieren lokal.',icon:'/icon-192.svg'});toast('Test-Benachrichtigung gesendet')}else await enableNotifications()}
function pct(v){return `${(Number(v||0)*100).toFixed(1)}%`}
function card(s){const l=s.side==='LONG';const readiness=s.model_ready?'MODEL':'RULE';return `<article class="glass setup-card"><div class="setup-top"><div><span class="symbol">${s.symbol}</span><span class="badge ${l?'side-long':'side-short'}">${s.side}</span><span class="badge">${s.mode}</span><span class="badge">${readiness}</span></div><div class="score">${s.confidence}<span>/100</span></div></div><div class="setup-price">${Number(s.entry).toLocaleString('de-DE',{maximumFractionDigits:8})}</div><div class="setup-meta"><div><small>WAHRSCHEINLICHKEIT</small><b>${pct(s.probability)}</b></div><div><small>EV</small><b>${Number(s.expected_value_r||0)>=0?'+':''}${Number(s.expected_value_r||0).toFixed(2)}R</b></div><div><small>R:R</small><b>1:${s.risk_reward}</b></div></div><div class="setup-meta"><div><small>STOP</small><b>${Number(s.stop_loss).toLocaleString('de-DE',{maximumFractionDigits:8})}</b></div><div><small>TP1</small><b>${Number(s.take_profit_1).toLocaleString('de-DE',{maximumFractionDigits:8})}</b></div><div><small>TP2</small><b>${Number(s.take_profit_2).toLocaleString('de-DE',{maximumFractionDigits:8})}</b></div></div><div class="setup-reason">${(s.reasons||[]).slice(0,3).join(' · ')}</div><div class="trade-actions"><button class="${l?'buy':'sell'}" data-side="${s.side}" data-symbol="${s.symbol}" data-mode="${s.mode}">${l?'LONG eröffnen':'SHORT eröffnen'}</button></div></article>`}
function render(){let a=state.setups.filter(s=>state.filter==='ALL'||state.filter===s.side||state.filter===s.mode);$('#setupGrid').innerHTML=a.length?a.slice(0,9).map(card).join(''):'<div class="empty-state">Keine passenden Setups gefunden.</div>';$('#setupCount').textContent=state.setups.length;$('#scalpSignals').textContent=state.setups.filter(s=>s.mode==='SCALP').length;$('#swingSignals').textContent=state.setups.filter(s=>s.mode==='SWING').length;bind();renderScanner()}
function renderScanner(){let a=state.setups.filter(s=>state.filter==='ALL'||state.filter===s.side||state.filter===s.mode);$('#scannerTable').innerHTML=a.length?'<div class="scanner-row header"><span>SYMBOL</span><span>SEITE</span><span>MODE</span><span>P</span><span>EV</span><span></span></div>'+a.map(s=>`<div class="scanner-row"><strong>${s.symbol}</strong><span class="${s.side==='LONG'?'side-long':'side-short'}">${s.side}</span><span>${s.mode}</span><strong>${pct(s.probability)}</strong><span>${Number(s.expected_value_r||0)>=0?'+':''}${Number(s.expected_value_r||0).toFixed(2)}R</span><button class="ghost-btn" data-side="${s.side}" data-symbol="${s.symbol}" data-mode="${s.mode}">Paper Trade</button></div>`).join(''):'<div class="empty-state">Noch keine Setups.</div>';bind()}
function bind(){$$('[data-side]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await fetch(`/trade/${b.dataset.mode}/${b.dataset.side}/${b.dataset.symbol}`,{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.detail||'Trade abgelehnt');toast(`${b.dataset.mode} ${b.dataset.side} ${b.dataset.symbol} eröffnet`);loadPositions()}catch(e){toast(e.message)}finally{b.disabled=false}})}
async function scan(){const b=$('#scanBtn');b.disabled=true;b.textContent='⟳ Analyse…';try{const r=await fetch(`/scan?mode=${state.mode}`),d=await r.json();state.setups=(d.setups||[]).filter(x=>x.confidence).map(x=>({...x,mode:x.mode||state.mode})).sort((a,b)=>(b.probability??b.confidence/100)-(a.probability??a.confidence/100));render();toast(`${state.setups.length} ${state.mode}-Setups gefunden`)}catch{toast('Scanner nicht erreichbar')}finally{b.disabled=false;b.textContent='⚡ Scan starten'}}
async function loadPositions(){try{const r=await fetch('/positions'),d=await r.json();$('#equity').textContent=money(d.equity);$('#pnl').innerHTML=`${money(d.realized_pnl)} <span>${d.equity?((d.realized_pnl/d.equity)*100).toFixed(2):'0.00'}%</span>`;$('#openTrades').textContent=(d.positions||[]).length;$('#positionsGrid').innerHTML=d.positions?.length?d.positions.map(p=>`<article class="glass position-card"><div class="position-top"><strong>${p.symbol}</strong><span class="${p.side==='LONG'?'side-long':'side-short'}">${p.side} · ${p.mode}</span></div><div class="position-pnl">${p.entry.toLocaleString('de-DE')} → ${p.take_profit.toLocaleString('de-DE')}</div><div class="position-bar"><i></i></div><p style="color:var(--muted);font-size:11px">SL ${p.stop_loss} · TP ${p.take_profit} · ${p.timeframe}</p></article>`).join(''):'<div class="empty-state">Keine offenen Paper-Trades.</div>'}catch{}}
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));$('#pageTitle').textContent=b.querySelector('span').textContent});
$$('.mode').forEach(b=>b.onclick=async()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;await scan()});
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render()});
$('#scanBtn').onclick=scan;$('#scanSecondary').onclick=scan;$('#refreshBtn').onclick=()=>{loadPositions();scan()};$('#notifyBtn').onclick=enableNotifications;$('#notifySettingsBtn').onclick=testNotification;$('#killSwitch').onclick=()=>{toast('Emergency Stop aktiviert — neue Trades blockieren');$('#engineLabel').textContent='Emergency stop aktiv';$('#engineLabel').style.color='var(--red)'};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});loadPositions();setInterval(loadPositions,10000);scan();