const AUTO_SCAN_KEY='tradenex_auto_scan';
const qs=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setAutoScanButton(enabled){const b=qs('#autoScanBtn');if(!b)return;b.textContent=enabled?'⚡ AUTO SCAN · AN':'⏸ AUTO SCAN · AUS';b.className=enabled?'primary-btn':'ghost-btn';b.dataset.enabled=String(enabled)}
async function ensureBothEngines(){try{const r=await fetch('/notifications/settings',{cache:'no-store'});if(!r.ok)return;const s=await r.json();if(s.scalp_enabled===true&&s.swing_enabled===true)return;await fetch('/notifications/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,scalp_enabled:true,swing_enabled:true})})}catch{}}
function ensureStatusBar(){let bar=qs('#autoStatusBar');if(bar)return bar;const top=qs('.topbar');if(!top)return null;bar=document.createElement('section');bar.id='autoStatusBar';bar.className='glass';bar.style.cssText='margin:14px 0 18px;padding:16px 20px;display:flex;align-items:center;justify-content:space-between;gap:16px';bar.innerHTML='<div><strong id="autoStatusTitle">🟢 AUTO TRADING AKTIV</strong><div id="autoStatusSub" style="color:var(--muted);font-size:12px;margin-top:5px">SCALP + SWING · Scanner · Auto-Execution · Position Monitoring</div></div><div style="text-align:right"><strong id="autoOpenCount">0 offene Trades</strong><div id="autoScanTime" style="color:var(--muted);font-size:11px;margin-top:5px">Scanner startet…</div></div>';top.insertAdjacentElement('afterend',bar);return bar}
function renderScannerFromSetups(items){const box=qs('#scannerTable');if(!box)return;const list=(items||[]).filter(Boolean);box.innerHTML=list.length?'<div class="scanner-row header"><span>SYMBOL</span><span>SEITE</span><span>MODE</span><span>WAHRSCHEINLICHKEIT</span><span>ENTRY</span><span>STATUS</span></div>'+list.map(x=>`<div class="scanner-row"><strong>${esc(x.symbol)}</strong><span class="${x.side==='LONG'?'side-long':'side-short'}">${esc(x.side)}</span><span>${esc(x.mode)}</span><strong>${(Number(x.probability||0)*100).toFixed(1)}%</strong><span>${Number(x.entry||0).toLocaleString('de-DE',{maximumFractionDigits:8})}</span><span class="result-pill">AUTO</span></div>`).join(''):'<div class="empty-state">Aktuell keine handelbaren Chancen.</div>'}
function renderPositionUI(positions){const box=qs('#positionsGrid');if(!box)return;box.innerHTML=positions.length?positions.map(p=>`<article class="glass position-card"><div class="position-top"><strong>${esc(p.symbol)}</strong><span class="${p.side==='LONG'?'side-long':'side-short'}">${esc(p.side)} · ${esc(p.mode)}</span></div><div class="position-pnl">Entry ${Number(p.entry||0).toLocaleString('de-DE',{maximumFractionDigits:8})}</div><div class="position-bar"><i></i></div><p style="color:var(--muted);font-size:11px">SL ${Number(p.stop_loss||0).toLocaleString('de-DE',{maximumFractionDigits:8)} · TP ${Number(p.tp2||p.tp1||0).toLocaleString('de-DE',{maximumFractionDigits:8)} · Trail ${Number(p.trailing_stop||0).toLocaleString('de-DE',{maximumFractionDigits:8)}</p></article>`).join(''):'<div class="empty-state">Keine offenen Trades.</div>'}
function renderHistoryUI(trades,status){const box=qs('#historyGrid');if(!box)return;const profit=qs('#historyProfit'),loss=qs('#historyLoss'),net=qs('#historyNet'),wr=qs('#historyWinrate'),count=qs('#historyCount');if(profit)profit.textContent='+'+money(status?.gross_profit||0);if(loss)loss.textContent=money(status?.gross_loss||0);if(net)net.textContent=(Number(status?.net_pnl||0)>=0?'+':'')+money(status?.net_pnl||0);if(wr)wr.textContent=status?.trades?Number(status.win_rate).toFixed(1)+'%':'—';if(count)count.textContent=`${status?.trades||0} Trades · ${status?.wins||0} W / ${status?.losses||0} L`;const closed=trades.filter(x=>x.status==='CLOSED');box.innerHTML=closed.length?'<div class="trade-history-list"><div class="trade-history-row header"><span>SYMBOL</span><span>SEITE</span><span>MODE</span><span>ENTRY</span><span>EXIT</span><span>GEBÜHREN</span><span>NETTO-P&L</span><span>STATUS</span></div>'+closed.map(x=>{const pnl=Number(x.pnl||0);return `<div class="trade-history-row ${pnl>0?'trade-win':'trade-loss'}"><strong>${esc(x.symbol)}</strong><span>${esc(x.side)}</span><span>${esc(x.mode)}</span><span>${Number(x.entry||0).toLocaleString('de-DE',{maximumFractionDigits:8})}</span><span>${Number(x.exit_price||0).toLocaleString('de-DE',{maximumFractionDigits:8})}</span><span>${money(x.total_fees||0)}</span><strong class="pnl-cell">${pnl>=0?'+':''}${money(pnl)}</strong><span class="result-pill">${pnl>0?'WIN':'LOSS'}</span></div>`}).join('')+'</div>':'<div class="empty-state">Noch keine geschlossenen Demo-Trades.</div>'}
async function syncScanner(){try{const r=await fetch('/scan/all',{cache:'no-store'});if(!r.ok)return;const d=await r.json();const all=(d.setups||[]).sort((a,b)=>(b.probability||0)-(a.probability||0));renderScannerFromSetups(all);const sc=qs('#scalpSignals'),sw=qs('#swingSignals'),sum=qs('#scanSummary'),chance=qs('#setupCount');if(sc)sc.textContent=d.SCALP?.qualified||0;if(sw)sw.textContent=d.SWING?.qualified||0;if(sum)sum.textContent=`${d.qualified_total||0} Chancen erkannt`;if(chance)chance.textContent=String(d.qualified_total||0)}catch{}}
async function syncDemoUI(){try{const [s,p,t]=await Promise.all([fetch('/demo/status',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/positions',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/trades?limit=100',{cache:'no-store'}).then(r=>r.json())]);const positions=p.items||[],trades=t.items||[],open=s.open_positions??positions.length;const openEl=qs('#openTrades');if(openEl)openEl.textContent=open;const autoOpen=qs('#autoOpenCount');if(autoOpen)autoOpen.textContent=`${open} offene Trades`;const eq=qs('#equity');if(eq)eq.textContent=money(s.equity);const pnl=qs('#pnl');if(pnl)pnl.innerHTML=`${money(s.net_pnl)} <span>${Number(s.pnl_pct||0).toFixed(2)}%</span>`;const daily=qs('#dailyPnl');if(daily)daily.textContent=money(s.net_pnl);const scanTime=qs('#autoScanTime');if(scanTime)scanTime.textContent=s.updated_at?`Letztes Update ${new Date(s.updated_at).toLocaleTimeString('de-DE')}`:'Scanner läuft…';renderPositionUI(positions);renderHistoryUI(trades,s)}catch{}}
async function refreshAutoScan(){try{const s=await(await fetch('/demo/status',{cache:'no-store'})).json();const enabled=!!s.enabled;localStorage.setItem(AUTO_SCAN_KEY,String(enabled));setAutoScanButton(enabled);ensureStatusBar();if(enabled)await ensureBothEngines();await syncDemoUI()}catch{setAutoScanButton(localStorage.getItem(AUTO_SCAN_KEY)!=='false')}}
async function toggleAutoScan(){const b=qs('#autoScanBtn'),current=b?.dataset.enabled==='true';try{const r=await fetch('/demo/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!current})}),d=await r.json();if(!r.ok)throw Error(d.detail||'Auto Scan konnte nicht geändert werden');localStorage.setItem(AUTO_SCAN_KEY,String(!!d.enabled));setAutoScanButton(!!d.enabled);if(d.enabled)await ensureBothEngines();await syncDemoUI();await syncScanner()}catch(e){const t=qs('#toast');if(t){t.textContent=e.message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}}}
function loadAsset(href){return new Promise(resolve=>{if(document.querySelector(`link[href="${href}"]`))return resolve();const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.onload=resolve;l.onerror=resolve;document.head.appendChild(l)})}
function loadScript(src){return new Promise(resolve=>{if(document.querySelector(`script[src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)})}
async function loadTheme(){if(window.__TRADENEX_THEME_LOADED)return;window.__TRADENEX_THEME_LOADED=true;await loadAsset('./theme.css?v=6');await loadAsset('./design-v3.css?v=3');await loadAsset('./ambience-engine.css?v=3');await loadScript('./theme.js?v=6')}
function initAutoScan(){if(qs('#autoScanBtn')){qs('#autoScanBtn').onclick=toggleAutoScan;refreshAutoScan();setInterval(refreshAutoScan,2000)}loadTheme();syncScanner();setInterval(syncDemoUI,3000);setInterval(syncScanner,10000)}
document.addEventListener('DOMContentLoaded',initAutoScan);