const $=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));
const n=v=>Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:8});
const dt=v=>v?new Date(v).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'medium'}):'—';
function toast(m){let t=document.createElement('div');t.className='toast show';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
function renderPositions(items){$('#positions').innerHTML=items.length?items.map(p=>`<article class="glass position-card"><div class="position-top"><strong>${p.symbol}</strong><span class="${p.side==='LONG'?'side-long':'side-short'}">${p.side} · ${p.mode}</span></div><div class="position-pnl">${n(p.entry)} → ${n(p.tp2)}</div><div class="position-bar"><i></i></div><p style="color:var(--muted);font-size:11px">SL ${n(p.stop_loss)} · TP1 ${n(p.tp1)} · Trail ${n(p.trailing_stop)} · Risiko ${n(p.quantity)}</p><small style="color:var(--muted)">Eröffnet: ${dt(p.opened_at)}</small></article>`).join(''):'<div class="empty-state">Keine offenen Demo-Positionen.</div>'}
function renderTrades(items){$('#trades').innerHTML=items.length?`<div class="scanner-list"><div class="scanner-row header"><span>SYMBOL</span><span>SEITE</span><span>MODE</span><span>P&L</span><span>R</span><span>RESULT</span><span>ABSCHLUSS</span></div>${items.map(t=>`<div class="scanner-row"><strong>${t.symbol}</strong><span class="${t.side==='LONG'?'side-long':'side-short'}">${t.side}</span><span>${t.mode}</span><span class="${Number(t.pnl)>=0?'side-long':'side-short'}">${Number(t.pnl)>=0?'+':''}${money(t.pnl)}</span><span>${Number(t.risk_r||0).toFixed(2)}R</span><span>${t.result}</span><span>${dt(t.closed_at)}</span></div>`).join('')}</div>`:'<div class="empty-state">Noch keine abgeschlossenen Demo-Trades.</div>'}
async function load(){try{const [s,p,t]=await Promise.all([fetch('/demo/status',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/positions',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/trades?limit=100',{cache:'no-store'}).then(r=>r.json())]);
$('#equity').textContent=money(s.equity);$('#pnl').textContent=`${s.net_pnl>=0?'+':''}${money(s.net_pnl)} · ${Number(s.pnl_pct||0).toFixed(2)}%`;
$('#winrate').textContent=s.trades?`${Number(s.win_rate).toFixed(1)}%`:'—';$('#closed').textContent=`${s.trades} Trades · ${s.wins} W / ${s.losses} L`;
$('#open').textContent=s.open_positions;$('#max').textContent=`Max. ${s.max_positions}`;$('#mode').textContent=s.enabled?'RUNNING':'STOPPED';$('#demoTag').textContent=s.enabled?'RUNNING':'STOPPED';$('#demoTag').className=s.enabled?'tag live':'tag';$('#toggle').textContent=s.enabled?'STOPPEN':'STARTEN';
$('#budget').value=String(s.budget);$('#risk').value=(Number(s.risk_per_trade)*100).toFixed(2);$('#maxPos').value=String(s.max_positions);
let summary=document.querySelector('#demoSummary');if(summary)summary.innerHTML=`<div class="hero-grid"><div class="glass metric-card"><span>GESAMTGEWINN</span><strong class="side-long">+${money(s.gross_profit||0)}</strong><small>Positive Abschlüsse</small></div><div class="glass metric-card"><span>GESAMTVERLUST</span><strong class="side-short">${money(s.gross_loss||0)}</strong><small>Negative Abschlüsse</small></div><div class="glass metric-card"><span>NETTO-P&L</span><strong>${s.net_pnl>=0?'+':''}${money(s.net_pnl||0)}</strong><small>Stand ${dt(s.updated_at)}</small></div><div class="glass metric-card"><span>WINRATE</span><strong>${s.trades?Number(s.win_rate).toFixed(1)+'%':'—'}</strong><small>${s.wins} W / ${s.losses} L</small></div></div>`;
renderPositions(p.items||[]);renderTrades(t.items||[]);}catch{toast('Demo API nicht erreichbar')}}
async function apply(){try{const budget=Number($('#budget').value),risk=Number($('#risk').value),maxPos=Number($('#maxPos').value);if(!Number.isFinite(budget)||budget<=0)throw Error('Budget muss größer als 0 sein');const r=await fetch('/demo/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({budget,risk_per_trade:risk/100,max_positions:maxPos})}),d=await r.json();if(!r.ok)throw Error(d.detail||'Konfiguration abgelehnt');$('#budget').value=d.budget;$('#risk').value=(Number(d.risk_per_trade)*100).toFixed(2);$('#maxPos').value=d.max_positions;toast(`Demo-Budget ${money(d.budget)} gespeichert`);await load()}catch(e){toast(e.message)}}
async function toggle(){const running=$('#mode').textContent==='RUNNING';const r=await fetch('/demo/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!running})}),d=await r.json();if(!r.ok){toast(d.detail||'Fehler');return}toast(!running?'Demo gestartet':'Demo gestoppt');await load()}
async function reset(){if(!confirm('Demo wirklich zurücksetzen? Alle virtuellen Demo-Trades werden gelöscht. Das Budget bleibt erhalten.'))return;const r=await fetch('/demo/reset',{method:'POST'}),d=await r.json();if(!r.ok){toast(d.detail||'Reset fehlgeschlagen');return}toast('Demo zurückgesetzt');await load()}
$('#apply').onclick=apply;$('#toggle').onclick=toggle;$('#reset').onclick=reset;$('#refresh').onclick=load;load();setInterval(load,3000);