const $=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0));
const n=v=>Number(v||0).toLocaleString('de-DE',{maximumFractionDigits:8});
const dt=v=>v?new Date(v).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'medium'}):'—';
function toast(m){let t=document.createElement('div');t.className='toast show';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}

function liveMarkToMarket(positions, marketItems){
  const prices=new Map((marketItems||[]).filter(x=>x&&x.symbol&&Number.isFinite(Number(x.price))).map(x=>[x.symbol,Number(x.price)]));
  let unrealized=0;
  const enriched=(positions||[]).map(p=>{
    const current=prices.has(p.symbol)?prices.get(p.symbol):Number(p.entry);
    const entry=Number(p.entry);
    const qty=Number(p.quantity||0);
    const pnl=(p.side==='LONG'?(current-entry):(entry-current))*qty;
    unrealized+=pnl;
    return {...p,current_price:current,unrealized_pnl:pnl};
  });
  return {positions:enriched,unrealized_pnl:unrealized};
}

function renderPositions(items){$('#positions').innerHTML=items.length?items.map(p=>`<article class="glass position-card"><div class="position-top"><strong>${p.symbol}</strong><span class="${p.side==='LONG'?'side-long':'side-short'}">${p.side} · ${p.mode}</span></div><div class="position-pnl">${n(p.entry)} → ${n(p.current_price)}</div><div class="position-bar"><i></i></div><p style="color:var(--muted);font-size:11px">SL ${n(p.stop_loss)} · TP1 ${n(p.tp1)} · Trail ${n(p.trailing_stop)} · Risiko ${n(p.quantity)}</p><strong class="${Number(p.unrealized_pnl)>=0?'side-long':'side-short'}" style="font-size:13px">Live P&L ${Number(p.unrealized_pnl)>=0?'+':''}${money(p.unrealized_pnl)}</strong><small style="color:var(--muted)">Start: ${dt(p.opened_at)} · Ende: OPEN</small></article>`).join(''):'<div class="empty-state">Keine offenen Demo-Positionen.</div>'}

function renderTrades(items, openPositions){
  const liveById=new Map((openPositions||[]).map(p=>[p.id,p]));
  $('#trades').innerHTML=items.length?`<div class="scanner-list"><div class="scanner-row header"><span>SYMBOL</span><span>SEITE</span><span>MODE</span><span>STATUS</span><span>P&L</span><span>R</span><span>START</span><span>ENDE</span></div>${items.map(t=>{const live=liveById.get(t.position_id);const pnl=t.status==='OPEN'?(live?.unrealized_pnl??null):t.pnl;return `<div class="scanner-row"><strong>${t.symbol}</strong><span class="${t.side==='LONG'?'side-long':'side-short'}">${t.side}</span><span>${t.mode}</span><span class="${t.status==='OPEN'?'side-long':(Number(t.pnl)>=0?'side-long':'side-short')}">${t.status==='OPEN'?'OPEN':t.result}</span><span class="${Number(pnl)>=0?'side-long':'side-short'}">${pnl==null?'—':(Number(pnl)>=0?'+':'')+money(pnl)}</span><span>${t.risk_r==null?'—':Number(t.risk_r).toFixed(2)+'R'}</span><span>${dt(t.opened_at)}</span><span>${t.status==='OPEN'?'OPEN':dt(t.closed_at)}</span></div>`}).join('')}</div>`:'<div class="empty-state">Noch keine Demo-Trades im Journal.</div>'
}

function renderScan(s){const scalp=s.scalp||{},swing=s.swing||{};$('#scalpScanned').textContent=scalp.scanned??0;$('#scalpQualified').textContent=scalp.qualified??0;$('#scalpRejected').textContent=`${scalp.rejected??0} verworfen`;$('#scalpErrors').textContent=`${scalp.errors??0} Fehler`;$('#swingScanned').textContent=swing.scanned??0;$('#swingQualified').textContent=swing.qualified??0;$('#swingRejected').textContent=`${swing.rejected??0} verworfen`;$('#swingErrors').textContent=`${swing.errors??0} Fehler`;$('#scanClock').textContent=s.last_scan_at?`Letzter Scan ${dt(s.last_scan_at)}`:'Noch kein Scan';$('#lastScanText').textContent=s.last_scan_at?`Scan ${dt(s.last_scan_at)}`:'Noch kein Scan';const opened=$('#openedCycle');if(opened)opened.textContent=`+${s.opened_last_cycle??0} neu eröffnet`;const b=s.best_setup;$('#bestSetup').innerHTML=b?`<strong>${b.symbol} · ${b.side} · ${b.mode}</strong> · Probability ${(Number(b.probability||0)*100).toFixed(1)}% · Confidence ${b.confidence}/100 · EV ${Number(b.expected_value_r||0)>=0?'+':''}${Number(b.expected_value_r||0).toFixed(2)}R · Entry ${n(b.entry)}`:'Kein aktuell qualifiziertes Setup. Der Bot analysiert weiter.';const err=s.last_error;$('#scanError').style.display=err?'block':'none';$('#scanError').textContent=err?`Letzter Fehler: ${err}`:''}

async function load(){try{const [s,p,t,scan,m]=await Promise.all([fetch('/demo/status',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/positions',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/trades?limit=100',{cache:'no-store'}).then(r=>r.json()),fetch('/demo/scan',{cache:'no-store'}).then(r=>r.json()),fetch('/market/overview',{cache:'no-store'}).then(r=>r.json())]);const live=liveMarkToMarket(p.items||[],m.items||[]);const realized=Number(s.net_pnl||0);const unrealized=Number(live.unrealized_pnl||0);const total=realized+unrealized;const markEquity=Number(s.budget||0)+total;$('#equity').textContent=money(markEquity);$('#pnl').innerHTML=`${total>=0?'+':''}${money(total)} <span>Realized ${realized>=0?'+':''}${money(realized)} · Unrealized ${unrealized>=0?'+':''}${money(unrealized)}</span>`;$('#winrate').textContent=s.trades?`${Number(s.win_rate).toFixed(1)}%`:'—';$('#closed').textContent=`${s.trades} geschlossen · ${s.wins} W / ${s.losses} L`;$('#open').textContent=`${s.open_positions} / ${s.target_open_positions}`;$('#max').textContent=`${s.free_slots} freie Slots`;$('#mode').textContent=s.enabled?'RUNNING':'STOPPED';$('#demoTag').textContent=s.enabled?'RUNNING':'STOPPED';$('#demoTag').className=s.enabled?'tag live':'tag';$('#toggle').textContent=s.enabled?'STOPPEN':'STARTEN';$('#budget').value=String(s.budget);$('#risk').value=(Number(s.risk_per_trade)*100).toFixed(2);$('#maxPos').value=String(s.max_positions);let summary=document.querySelector('#demoSummary');if(summary)summary.innerHTML=`<div class="hero-grid"><div class="glass metric-card"><span>REALIZED P&L</span><strong class="${realized>=0?'side-long':'side-short'}">${realized>=0?'+':''}${money(realized)}</strong><small>Geschlossene Trades</small></div><div class="glass metric-card"><span>UNREALIZED P&L</span><strong class="${unrealized>=0?'side-long':'side-short'}">${unrealized>=0?'+':''}${money(unrealized)}</strong><small>Aktuelle offene Positionen</small></div><div class="glass metric-card"><span>GESAMT P&L</span><strong>${total>=0?'+':''}${money(total)}</strong><small>Stand ${dt(new Date().toISOString())}</small></div><div class="glass metric-card"><span>WINRATE</span><strong>${s.trades?Number(s.win_rate).toFixed(1)+'%':'—'}</strong><small>${s.wins} W / ${s.losses} L</small></div></div>`;renderScan(scan);renderPositions(live.positions);renderTrades(t.items||[],live.positions)}catch{toast('Demo API nicht erreichbar')}}

async function apply(){try{const budget=Number($('#budget').value),risk=Number($('#risk').value),maxPos=Number($('#maxPos').value);if(!Number.isFinite(budget)||budget<=0)throw Error('Budget muss größer als 0 sein');const r=await fetch('/demo/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({budget,risk_per_trade:risk/100,max_positions:maxPos})}),d=await r.json();if(!r.ok)throw Error(d.detail||'Konfiguration abgelehnt');$('#budget').value=d.budget;$('#risk').value=(Number(d.risk_per_trade)*100).toFixed(2);$('#maxPos').value=d.max_positions;toast(`Demo-Budget ${money(d.budget)} gespeichert`);await load()}catch(e){toast(e.message)}}
async function toggle(){const running=$('#mode').textContent==='RUNNING';const r=await fetch('/demo/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!running})}),d=await r.json();if(!r.ok){toast(d.detail||'Fehler');return}toast(!running?'Demo gestartet':'Demo gestoppt');await load()}
async function reset(){if(!confirm('Demo wirklich zurücksetzen? Alle virtuellen Demo-Trades werden gelöscht. Das Budget bleibt erhalten.'))return;const r=await fetch('/demo/reset',{method:'POST'}),d=await r.json();if(!r.ok){toast(d.detail||'Reset fehlgeschlagen');return}toast('Demo zurückgesetzt');await load()}

$('#apply').onclick=apply;$('#toggle').onclick=toggle;$('#reset').onclick=reset;$('#refresh').onclick=load;load();setInterval(load,2000);