(()=>{
  const KEY='tradenex_visual_settings_v3';
  const defaults={preset:'tradenex',accent:'#55e7ff',accent2:'#8c5cff',accent3:'#ff39d1',metal:'#c8d0df',background:'reactor',motion:true,glow:12,panel:88,logoBrightness:100,logoGlow:100,effectStrength:72,advanced:{material:'glass',density:'normal',font:'system',headingWeight:800,numberWeight:900,letterSpacing:0,uiScale:100,animationSpeed:100,transitionSpeed:100,particleCount:70,particleSize:100,particleSpeed:100,depth:70,parallax:40,bloom:65,noise:12,scanSpeed:65,gridSize:54,radarSpeed:55,coreRotation:60,neuralLines:70,backgroundDim:45,performance:'balanced',fps:60,cinematic:false,glitch:false,chromatic:false,profitFx:true,lossFx:true,setupFx:true,themeName:'TRADENEX Core'}};
  const palettes={
    tradenex:['TRADENEX Core','#55e7ff','#8c5cff','#ff39d1','#c8d0df','#02040a'],
    blackgold:['Black / Gold','#ffca4a','#9f6d16','#ffe6a3','#f0cf72','#050403'],
    platinum:['Platinum / Black','#e7eef7','#9eb0c2','#ffffff','#d6e0ea','#040607'],
    silver:['Silver / Black','#d7e2ef','#8fa3bd','#f4f7fb','#ffffff','#030507'],
    obsidian:['Obsidian / Ruby','#ff5c78','#a92749','#ff9daf','#e7c5cc','#050205'],
    emerald:['Emerald / Black','#42f5a7','#159b6a','#a9ffd8','#c9f7e4','#020604'],
    ice:['Ice / Deep Navy','#9cf7ff','#5ea6ff','#d5fbff','#eefcff','#020610'],
    ocean:['Ocean Depth','#32d7d1','#1877ff','#7ee8ff','#d6ffff','#011116'],
    plasma:['Plasma / Black','#d24cff','#6d5cff','#ff6b9d','#f3d8ff','#06020b'],
    solar:['Solar Gold / Violet','#ffd15c','#ff8c42','#9d64ff','#fff0b8','#090505'],
    crimson:['Crimson / Platinum','#ff4a4a','#8e1e35','#e8eef7','#f4f6fb','#080203'],
    holographic:['Holographic','#62f3ff','#b168ff','#ff5fcf','#eefcff','#03050a'],
    cyanblue:['Cyan / Electric Blue','#36f6ff','#356aff','#8c8cff','#e2fbff','#02070b'],
    violetgold:['Violet / Gold','#a36bff','#5b44d6','#ffd45a','#f7e2a3','#06030b'],
    carbonred:['Carbon / Red','#ff415d','#77192d','#ff8d9d','#d7dce6','#040305'],
    stealth:['Stealth / Ice','#9cb7d7','#596d8b','#dff1ff','#e9f5ff','#030609'],
    arctic:['Arctic Silver','#b8f5ff','#83c7ff','#e9ffff','#ffffff','#02070b'],
    toxic:['Toxic Lime','#baff31','#4fae16','#e6ff8b','#e5f6c6','#030601'],
    amber:['Amber / Obsidian','#ffb64d','#a86219','#ffe0a1','#f5dbaf','#070402'],
    royal:['Royal Violet','#7859ff','#3324a8','#c9adff','#e5dfff','#05030c'],
    graphite:['Graphite / Silver','#aeb8c7','#66758b','#f3f7ff','#d8dee7','#06080b'],
    cyberpink:['Cyber Pink','#ff43c8','#7b41ff','#ff9fda','#ffe5f6','#08030b'],
    matrix:['Matrix / Black','#55ff9b','#15995b','#caffdd','#c8ffe0','#020603'],
    deepblue:['Deep Blue','#4f8cff','#132b88','#8ed8ff','#dceaff','#02040c']
  };
  const effects=[
    ['reactor','Reactor Core','Kinetischer Energie-Kern','tn-thumb-reactor'],['singularity','Singularity','Black-Hole Zentrum','tn-thumb-void'],['quantum-web','Quantum Web','Tiefes Netzwerk','tn-thumb-neural'],['ai-neural','AI Neural','Neuronales Daten-Netz','tn-thumb-neural'],['energy-tunnel','Energy Tunnel','Warp-Tunnel','tn-thumb-tunnel'],['galaxy-drift','Galaxy Drift','Parallax-Sternenstrom','tn-thumb-stars'],['deep-space','Deep Space','Kosmischer Raum','tn-thumb-stars'],['cyber-city','Cyber City','Futuristische Skyline','tn-thumb-city'],['electric-vortex','Electric Vortex','Elektrischer Wirbel','tn-thumb-pulse'],['holo-rings','Holo Rings','Hologramm-Orbits','tn-thumb-orbit'],['data-core','Data Core','Datenkern','tn-thumb-orbit'],['digital-ocean','Digital Ocean','Wellenfeld','tn-thumb-wave'],['particle-storm','Particle Storm','Partikelsturm','tn-thumb-stars'],['hex-flux','Hex Flux','Energie-Hexmesh','tn-thumb-hex'],['radar','Radar Sweep','Radar-Hologramm','tn-thumb-orbit'],['matrix','Matrix Flow','Digital Rain','tn-thumb-rain'],['cyber-grid','Cyber Grid','Perspektivische Grid-Welt','tn-thumb-grid'],['aurora','Aurora Veil','Lichtschleier','tn-thumb-radial'],['nebula','Nebula Drift','Nebelwolken','tn-thumb-radial'],['pulse','Neon Pulse','Leuchtender Energiepuls','tn-thumb-pulse'],['storm','Electric Storm','Elektrische Störungen','tn-thumb-pulse'],['circuit','Circuit Flux','Leiterbahnen','tn-thumb-grid'],['synthwave','Synthwave Horizon','Retro-Future Horizon','tn-thumb-wave'],['scan','Holographic Scan','Holo-Scan','tn-thumb-grid'],['void','Clean Void','Tiefes Schwarz','tn-thumb-void'],['constellation','Constellation','Sternbild-Netz','tn-thumb-neural'],['orbital','Orbital Command','Umlaufende Daten','tn-thumb-orbit'],['monolith','Monolith','Vertikaler Energiepylon','tn-thumb-reactor'],['plasma','Plasma Field','Plasma-Wolken','tn-thumb-pulse'],['fractal','Fractal Bloom','Fraktale Energie','tn-thumb-neural']
  ];
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clone=()=>JSON.parse(JSON.stringify(defaults));
  let state={};
  const read=()=>{try{return Object.assign(clone(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone()}};
  state=read();
  const saveLocal=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const debouncedServer=(()=>{let t;return()=>{clearTimeout(t);t=setTimeout(async()=>{try{await fetch('/notifications/visual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,logo_brightness:state.logoBrightness,logo_glow:state.logoGlow,effect_strength:state.effectStrength})})}catch{}}},500)}})();
  async function restore(){try{const r=await fetch('/notifications/visual',{cache:'no-store'});if(r.ok){const s=await r.json();state={...state,...s,logoBrightness:s.logo_brightness??state.logoBrightness,logoGlow:s.logo_glow??state.logoGlow,effectStrength:s.effect_strength??state.effectStrength,advanced:{...state.advanced,...(s.advanced||{})}};saveLocal()}}catch{};apply();}
  function apply(){const root=document.documentElement.style,a=state.advanced||{};root.setProperty('--theme-accent',state.accent);root.setProperty('--theme-accent-2',state.accent2);root.setProperty('--theme-accent-3',state.accent3);root.setProperty('--theme-metal',state.metal);root.setProperty('--theme-bg',palettes[state.preset]?.[5]||'#02040a');root.setProperty('--theme-glow',String(state.glow/100));root.setProperty('--theme-panel-alpha',String(state.panel/100));root.setProperty('--theme-effect-strength',String(state.effectStrength/100));root.setProperty('--cyan',state.accent);root.setProperty('--blue',state.accent2);root.setProperty('--violet',state.accent2);root.setProperty('--magenta',state.accent3);root.setProperty('--silver',state.metal);root.setProperty('--theme-density',a.density||'normal');root.setProperty('--theme-ui-scale',`${a.uiScale||100}%`);root.setProperty('--theme-animation-speed',`${(a.animationSpeed||100)/100}`);root.setProperty('--theme-transition-speed',`${(a.transitionSpeed||100)/100}`);root.setProperty('--theme-glow-px',`${Math.max(0,state.glow)}px`);root.setProperty('--theme-panel-opacity',`${state.panel}%`);document.body.dataset.themePreset=state.preset;document.body.dataset.ambience=state.background;document.body.dataset.material=a.material||'glass';document.body.dataset.uiDensity=a.density||'normal';document.body.dataset.performance=a.performance||'balanced';document.body.classList.toggle('motion-off',!state.motion);document.body.classList.toggle('cinematic-mode',!!a.cinematic);document.body.classList.toggle('tn-glitch',!!a.glitch);document.body.classList.toggle('tn-chromatic',!!a.chromatic);document.body.style.setProperty('--theme-font',a.font||'system');const logo=$('.sidebar .brand-mark img');if(logo)logo.style.filter=`brightness(${state.logoBrightness/100}) drop-shadow(0 0 ${Math.max(4,24*state.logoGlow/100)}px ${state.accent}) saturate(1.08)`;const amb=$('#tradenexAmbience');if(amb){amb.dataset.effect=state.background;amb.dataset.motion=String(state.motion);amb.dataset.fps=String(a.fps||60)};$$('#design .tn-pro-tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===($('.tn-pro-panel.active')?.dataset.panel)));$$('#design .tn-effect-card').forEach(b=>b.classList.toggle('active',b.dataset.effect===state.background));updateValues();}
  function set(k,v){state[k]=v;saveLocal();apply();debouncedServer();}
  function setA(k,v){state.advanced[k]=v;saveLocal();apply();debouncedServer();}
  function updateValues(){$$('.tn-pro-value').forEach(el=>{const key=el.dataset.key;const v=key.startsWith('a.')?(state.advanced||{})[key.slice(2)]:state[key];if(v!==undefined)el.textContent=typeof v==='number'?`${v}%`:String(v)});const st=$('#tnProStatus');if(st)st.textContent=`GESPEICHERT · ${state.advanced.themeName||palettes[state.preset]?.[0]||'Custom'}`;}
  function paletteCards(){return Object.entries(palettes).map(([id,p])=>`<button class="tn-swatch" data-preset="${id}" style="background:linear-gradient(120deg,${p[1]} 0 30%,${p[2]} 31% 62%,${p[3]} 63% 78%,${p[5]} 79%);"><span>${p[0]}</span></button>`).join('')}
  function effectCards(){return effects.map(([id,n,d,thumb])=>`<button class="tn-effect-card" data-effect="${id}"><div class="tn-effect-thumb ${thumb}"></div><b>${n}</b><small>${d}</small></button>`).join('')}
  function range(label,key,min,max,step=1){const k=key.startsWith('a.')?key.slice(2):key;const v=key.startsWith('a.')?(state.advanced||{})[k]:state[k];return`<div class="tn-pro-field"><label>${label}</label><div><input data-range="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${v??min}"><span class="tn-pro-value" data-key="${key}">${v??min}%</span></div></div>`}
  function toggle(label,key){const v=(state.advanced||{})[key]??false;return`<div class="tn-pro-field"><label>${label}</label><button class="tn-pro-toggle ${v?'on':''}" data-toggle="${key}" aria-label="${label}"></button></div>`}
  function mount(){if(!$('#design')||$('#tnProStudio'))return false;const d=$('#design');const studio=document.createElement('div');studio.id='tnProStudio';studio.className='tn-pro-shell';studio.innerHTML=`<div class="tn-pro-top"><div class="tn-pro-brand"><div class="tn-pro-badge">✦</div><div><b>TRADENEX DESIGN STUDIO</b><small>Visual command center · persistent workspace</small></div></div><div class="tn-pro-actions"><button id="tnSave" class="tn-pro-btn primary">✓ Design speichern</button><button id="tnRandom" class="tn-pro-btn">⤨ Randomize</button><button id="tnReset" class="tn-pro-btn">↺ Standard</button></div></div><div class="tn-pro-tabs">${['themes','colors','materials','backgrounds','motion','cyber','typography','logo','trading','performance','saved'].map((x,i)=>`<button class="tn-pro-tab ${i===0?'active':''}" data-panel="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><div class="tn-pro-panels">
<div class="tn-pro-panel active" data-panel="themes"><div class="tn-pro-card"><h4>Premium Farbwelten</h4><p>Komplette TRADENEX-Identitäten mit Primär-, Sekundär-, Highlight- und Metallic-Farbe.</p><div class="tn-swatch-grid">${paletteCards()}</div></div></div>
<div class="tn-pro-panel" data-panel="colors"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Color Architecture</h4>${[['accent','Primärfarbe'],['accent2','Sekundärfarbe'],['accent3','Highlight'],['metal','Metallic'],].map(([k,n])=>`<div class="tn-pro-field"><label>${n}</label><input type="color" data-color="${k}" value="${state[k]}"></div>`).join('')}</div><div class="tn-pro-card"><h4>Color Harmony</h4>${range('Farbintensität','effectStrength',0,100)}${range('Glow','glow',0,30)}${range('Panel-Transparenz','panel',55,98)}</div><div class="tn-pro-card"><h4>Preview</h4><div class="tn-pro-mini-preview"></div><div class="tn-pro-note">Die Vorschau nutzt dieselbe Palette wie das echte UI.</div></div></div></div>
<div class="tn-pro-panel" data-panel="materials"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Material</h4><div class="tn-pro-field"><label>Oberfläche</label><select data-adv="material"><option value="glass">Glass</option><option value="carbon">Carbon Fiber</option><option value="metal">Brushed Metal</option><option value="holo">Holographic Glass</option><option value="matte">Matte Obsidian</option></select></div>${range('Blur','blur',0,36)}</div><div class="tn-pro-card"><h4>Depth</h4>${range('Border Brightness','borderBrightness',0,100)}${range('Inner Glow','innerGlow',0,100)}${range('Outer Glow','outerGlow',0,100)}${range('Shadow Strength','shadow',0,100)}</div><div class="tn-pro-card"><h4>Material Reflection</h4>${toggle('Reflections','reflection')}${toggle('Metallic Sweep','metalSweep')}${toggle('Holographic Tint','holoTint')}</div></div></div>
<div class="tn-pro-panel" data-panel="backgrounds"><div class="tn-pro-grid"><div class="tn-pro-card" style="grid-column:1/-1"><h4>Ambient Library</h4><p>Diese Szenen laufen in einer isolierten Canvas-Schicht hinter der UI.</p><div class="tn-effect-grid">${effectCards()}</div></div></div></div>
<div class="tn-pro-panel" data-panel="motion"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Animation</h4>${toggle('Animationen','animations')}${range('Gesamtgeschwindigkeit','animationSpeed',10,200)}${range('UI Transitions','transitionSpeed',10,200)}${range('Parallax','parallax',0,100)}${toggle('Cinematic Mode','cinematic')}</div><div class="tn-pro-card"><h4>Background Motion</h4>${range('Partikelanzahl','particleCount',10,100)}${range('Partikelgröße','particleSize',25,200)}${range('Partikelgeschwindigkeit','particleSpeed',10,200)}${range('Tiefenstaffelung','depth',0,100)}${range('Bloom','bloom',0,100)}</div><div class="tn-pro-card"><h4>Scan & Energy</h4>${range('Scan-Speed','scanSpeed',0,100)}${range('Grid Size','gridSize',20,120)}${range('Radar-Speed','radarSpeed',0,100)}${range('Core Rotation','coreRotation',0,100)}</div></div></div>
<div class="tn-pro-panel" data-panel="cyber"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Cyber FX</h4>${toggle('Glitch','glitch')}${toggle('Chromatic Aberration','chromatic')}${toggle('CRT Scanlines','crt')}${toggle('Digital Noise','noiseFx')}</div><div class="tn-pro-card"><h4>Signal</h4>${range('Noise','noise',0,100)}${range('Signal Distortion','distortion',0,100)}${range('Hologram Intensity','holoIntensity',0,100)}</div><div class="tn-pro-card"><h4>Lens</h4>${range('Bloom','bloom',0,100)}${range('Vignette','vignette',0,100)}${range('Light Leak','lightLeak',0,100)}</div></div></div>
<div class="tn-pro-panel" data-panel="typography"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Typography</h4><div class="tn-pro-field"><label>Font</label><select data-adv="font"><option value="system">System / Inter</option><option value="mono">Terminal Mono</option><option value="condensed">Condensed</option><option value="wide">Wide Tech</option></select></div>${range('Heading Weight','headingWeight',500,950)}${range('Number Weight','numberWeight',500,950)}${range('Letter Spacing','letterSpacing',-4,8)}</div><div class="tn-pro-card"><h4>UI Density</h4><div class="tn-pro-field"><label>Layout</label><select data-adv="density"><option value="compact">Compact</option><option value="normal">Normal</option><option value="spacious">Spacious</option></select></div>${range('UI Scale','uiScale',85,115)}</div><div class="tn-pro-card"><h4>Market Numbers</h4><div class="tn-pro-field"><label>Style</label><select data-adv="numberStyle"><option value="premium">Premium</option><option value="terminal">Terminal</option><option value="digital">Digital</option><option value="holographic">Holographic</option></select></div></div></div></div>
<div class="tn-pro-panel" data-panel="logo"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>TRADENEX Bull</h4>${range('Helligkeit','logoBrightness',60,140)}${range('Glow','logoGlow',0,160)}${toggle('Reflection','logoReflection')}${toggle('Tint','logoTint')}</div><div class="tn-pro-card"><h4>Launch Sequence</h4><div class="tn-pro-field"><label>Style</label><select data-adv="splash"><option value="particle-dissolve">Particle Dissolve</option><option value="scan-reveal">Scan Reveal</option><option value="hologram">Hologram</option><option value="energy-build">Energy Build</option><option value="digital-fragment">Digital Fragment</option></select></div>${range('Particle Amount','splashParticles',20,150)}${range('Dissolve Speed','splashSpeed',20,180)}</div><div class="tn-pro-card"><h4>Brand Motion</h4>${toggle('Sidebar Pulse','sidebarPulse')}${toggle('Dashboard Mark','dashboardMark')}${toggle('Loading Logo','loadingLogo')}</div></div></div>
<div class="tn-pro-panel" data-panel="trading"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Live Trading Visuals</h4>${toggle('Market Pulse','marketPulse')}${toggle('Probability Aura','probabilityAura')}${toggle('Setup Beacon','setupFx')}${toggle('Trade Entry FX','entryFx')}</div><div class="tn-pro-card"><h4>Result Feedback</h4>${toggle('Profit Burst','profitFx')}${toggle('Loss Warning','lossFx')}${toggle('TP Hit Animation','tpFx')}${toggle('SL Hit Animation','slFx')}</div><div class="tn-pro-card"><h4>Intensity</h4>${range('Probability Glow','probabilityGlow',0,100)}${range('Volatility Glow','volatilityGlow',0,100)}${range('Volume Heat','volumeGlow',0,100)}</div></div></div>
<div class="tn-pro-panel" data-panel="performance"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Rendering</h4><div class="tn-pro-field"><label>Mode</label><select data-adv="performance"><option value="balanced">Balanced</option><option value="quality">Maximum Quality</option><option value="performance">Performance</option><option value="low">Low Power</option></select></div><div class="tn-pro-field"><label>FPS</label><select data-adv="fps"><option>30</option><option>45</option><option>60</option><option>90</option><option>120</option></select></div>${toggle('Pause when minimized','pauseMinimized')}${toggle('Reduce effects on battery','batterySaver')}</div><div class="tn-pro-card"><h4>Safety</h4><div class="tn-pro-note">Alle Performance-Optionen betreffen ausschließlich Visuals und greifen nicht in Scanner, Binance oder Trade-Engine ein.</div>${toggle('Safe Visual Mode','safeVisual')}</div><div class="tn-pro-card"><h4>Live Preview</h4><div class="tn-pro-mini-preview"></div></div></div></div>
<div class="tn-pro-panel" data-panel="saved"><div class="tn-pro-grid"><div class="tn-pro-card"><h4>Saved Themes</h4><div id="tnSavedList"></div><div class="tn-pro-actions" style="margin-top:10px"><button id="tnSavePreset" class="tn-pro-btn primary">＋ Als Preset speichern</button></div></div><div class="tn-pro-card"><h4>Export / Import</h4><button id="tnExport" class="tn-pro-btn">Export JSON</button><label class="tn-pro-btn" style="display:inline-block;cursor:pointer">Import JSON<input id="tnImport" type="file" accept="application/json" style="display:none"></label><div class="tn-pro-note">Deine Designs werden als reine Visual-Konfiguration exportiert.</div></div><div class="tn-pro-card"><h4>Randomizer</h4><div class="tn-pro-note">Erzeugt eine neue Farb-, Material- und Effektkombination ohne Trading-Parameter zu verändern.</div></div></div></div>
</div><div class="tn-pro-footer"><span id="tnProStatus" class="tn-pro-status">GESPEICHERT</span><span class="tn-pro-status">Visual Layer only · Trading Engine untouched</span></div>`;
    d.insertBefore(studio,d.firstChild);
    bind(studio);apply();
    return true;
  }
  function bind(studio){
    $$('.tn-pro-tab',studio).forEach(b=>b.onclick=()=>{$$('.tn-pro-tab',studio).forEach(x=>x.classList.remove('active'));$$('.tn-pro-panel',studio).forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`.tn-pro-panel[data-panel="${b.dataset.panel}"]`,studio)?.classList.add('active')});
    $$('.tn-swatch',studio).forEach(b=>b.onclick=()=>{const p=palettes[b.dataset.preset];if(!p)return;state={...state,preset:b.dataset.preset,accent:p[1],accent2:p[2],accent3:p[3],metal:p[4]};state.advanced.themeName=p[0];saveLocal();apply();debouncedServer()});
    $$('.tn-effect-card',studio).forEach(b=>b.onclick=()=>{set('background',b.dataset.effect)});
    $$('[data-color]',studio).forEach(i=>i.oninput=e=>set(e.target.dataset.color,e.target.value));
    $$('[data-range]',studio).forEach(i=>i.oninput=e=>{const k=e.target.dataset.range;k.startsWith('a.')?setA(k.slice(2),Number(e.target.value)):set(k,Number(e.target.value))});
    $$('[data-adv]',studio).forEach(i=>{const k=i.dataset.adv;i.value=(state.advanced||{})[k]??i.value;i.onchange=e=>setA(k,e.target.value)});
    $$('[data-toggle]',studio).forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;const v=!Boolean((state.advanced||{})[k]);b.classList.toggle('on',v);setA(k,v)});
    $('#tnSave',studio).onclick=async()=>{saveLocal();try{await fetch('/notifications/visual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,logo_brightness:state.logoBrightness,logo_glow:state.logoGlow,effect_strength:state.effectStrength})})}catch{};const s=$('#tnProStatus');if(s)s.textContent='GESPEICHERT · '+new Date().toLocaleTimeString()};
    $('#tnReset',studio).onclick=()=>{state=clone();saveLocal();apply();debouncedServer()};
    $('#tnRandom',studio).onclick=()=>{const ids=Object.keys(palettes);const id=ids[Math.floor(Math.random()*ids.length)],p=palettes[id];state={...state,preset:id,accent:p[1],accent2:p[2],accent3:p[3],metal:p[4],background:effects[Math.floor(Math.random()*effects.length)][0]};state.advanced={...state.advanced,material:['glass','carbon','metal','holo','matte'][Math.floor(Math.random()*5)],cinematic:Math.random()>.55,themeName:p[0]};saveLocal();apply();debouncedServer()};
    $('#tnSavePreset',studio).onclick=()=>{const name=prompt('Name für das Design-Preset:',state.advanced.themeName||'Mein TRADENEX Theme');if(!name)return;const saved=JSON.parse(localStorage.getItem('tradenex_saved_themes')||'{}');saved[name]=state;localStorage.setItem('tradenex_saved_themes',JSON.stringify(saved));renderSaved()};
    $('#tnExport',studio).onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.advanced.themeName||'tradenex-theme')+'.json';a.click();URL.revokeObjectURL(a.href)};
    $('#tnImport',studio).onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...clone(),...JSON.parse(r.result),advanced:{...clone().advanced,...(JSON.parse(r.result).advanced||{})}};saveLocal();apply();debouncedServer();renderSaved()}catch{}};r.readAsText(f)};
    renderSaved();
  }
  function renderSaved(){const box=$('#tnSavedList');if(!box)return;const saved=JSON.parse(localStorage.getItem('tradenex_saved_themes')||'{}');box.innerHTML=Object.keys(saved).length?Object.keys(saved).map(n=>`<div class="tn-pro-saved" style="display:flex;justify-content:space-between;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid rgba(255,255,255,.04)"><span style="font-size:9px">${n}</span><span><button class="tn-pro-btn" data-load="${n}">Load</button><button class="tn-pro-btn tn-pro-danger" data-del="${n}">×</button></span></div>`).join(''):'<div class="tn-pro-note">Noch keine gespeicherten Themes.</div>';$$('[data-load]',box).forEach(b=>b.onclick=()=>{const s=JSON.parse(localStorage.getItem('tradenex_saved_themes')||'{}')[b.dataset.load];if(s){state=s;saveLocal();apply();debouncedServer()}});$$('[data-del]',box).forEach(b=>b.onclick=()=>{const s=JSON.parse(localStorage.getItem('tradenex_saved_themes')||'{}');delete s[b.dataset.del];localStorage.setItem('tradenex_saved_themes',JSON.stringify(s));renderSaved()})}
  window.__TRADENEX_DESIGN_READY=(async()=>{await restore();let tries=0;while(!mount()&&tries<80){await new Promise(r=>setTimeout(r,100));tries++}apply();})();
})();